services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${QB_UID:-1000}
      - PGID=${QB_GID:-1000}
      - TZ=${QB_TIMEZONE:-Etc/Kyiv}
      - WEBUI_PORT=${QB_WEB_UI_PORT:-8080}
      - TORRENTING_PORT=${QB_TORRENTING_PORT:-6881}
    volumes:
      - /mnt/smb/docker/qbittorrent/config:/config
      - /mnt/smb/media:/downloads
    ports:
      - ${QB_TORRENTING_PORT}:${QB_TORRENTING_PORT}
      - ${QB_TORRENTING_PORT}:${QB_TORRENTING_PORT}/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      homelab:
    labels:
      - traefik.enable=true
      - traefik.http.routers.qb.entrypoints=https
      - traefik.http.routers.qb.rule=Host(`${TRAEFIK_DOMAIN:-qb.site.com}`)
      - traefik.http.routers.qb.tls=true
      - traefik.http.routers.qb.tls.certresolver=cloudflare
      - traefik.http.services.qb.loadbalancer.server.port=${QB_WEB_UI_PORT}
networks:
  homelab:
    external: true