services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      internal:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    volumes:
      - jellyfin-cache:/cache
      - ${JELLYFIN_CONFIG_PATH:-./config}:/config
      - ${MEDIA_DIR_PATH:-./media}:/media
    devices:
      - /dev/dri/:/dev/dri/
    ports:
      - 8096:8096
    networks:
      internal:
      homelab:
    depends_on:
      - cloudflared
    labels:
      - traefik.enable=true
      - traefik.http.routers.jf-https.entrypoints=https
      - traefik.http.routers.jf-https.rule=Host(`${TRAEFIK_DOMAIN:-traefik.example.com}`)
      - traefik.http.routers.jf-https.tls=true
      - traefik.http.routers.jf-https.tls.certresolver=cloudflare
      - traefik.http.services.jf.loadbalancer.server.port=8096
volumes:
  jellyfin-cache:
networks:
  internal:
  homelab:
    external: true