services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    
    env_file:
      - path: ./.env
        required: true
      - path: /mnt/docker/jellyfin/.env
        required: false
    networks:
      - app_net
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    volumes:
      - jellyfin-cache:/cache:Z
      - /mnt/docker/jellyfin:/config
      - /media:/media
    devices:
      - /dev/dri/:/dev/dri/
    ports:
      - 8096:8096
    networks:
      - app_net
    depends_on:
      - cloudflared
volumes:
  jellyfin-cache:
networks:
  app_net: